name: 自动部署

on: # 触发条件
  push:
    branches:
      - main # 推送到 main 分支（这里的分支名很重要，不要弄错了

  workflow_dispatch: # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: 安装 Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_SECRET }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "QianF"
          git config --global user.email "576765349@qq.com"
          npm install hexo-cli -g

      - name: 生成静态文件
        run: |
          hexo clean
          git ls-files -z | while read -d '' path; do touch -d $(git log -1 --format="@%ct" "$path") "$path"; done
          hexo g

      - name: 部署
        run: |
          hexo deploy


          