name: 自动部署

# 当有改动推送时，启动Action
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: 安装 Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_SECRET }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "QianF"
          git config --global user.email "576765349@qq.com"

      - name: 生成静态文件
        run: |
          hexo clean
          hexo g

      - name: 部署
        run: |
          hexo deploy


          